# Script related constants
JOB_STATUS_NUM_POLLS = 'JOB_STATUS_NUM_POLLS'
JOB_STATUS_POLL_INTERVAL_SECONDS = 'JOB_STATUS_POLL_INTERVAL_SECONDS'
DELETE_BASE_DOWNLOAD_DIRECTORY_AFTER_EXPORT = 'DELETE_BASE_DOWNLOAD_DIRECTORY_AFTER_EXPORT'
BASE_DOWNLOAD_DIRECTORY = 'BASE_DOWNLOAD_DIRECTORY'
DB_URL = 'DB_URL'

# Export metadata related constants
DIFF_ACTION_COLUMN_NAME = '_DiffAction_'
DIFF_ACTION_INSERT = '+'

# Pandas DataFrame Dtype constants (see https://pandas.pydata.org/pandas-docs/stable/user_guide/basics.html#dtypes)
PANDAS_DF_NULLABLE_INTEGER_INT64_DTYPE = 'Int64'
PANDAS_DF_MIXED_DTYPE = 'object'
PANDAS_DF_FLOAT64_DTYPE = 'float64'
PANDAS_DF_BOOLEAN_DTYPE = 'boolean'
